name: Test

on: [ push, pull_request ]

jobs:

  test:
    strategy:
      fail-fast: false
      matrix:
        luaVersion: ['5.1', '5.2', '5.3', '5.4']
    runs-on: ubuntu-22.04
    name: test lua ${{ matrix.luaVersion }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup Lua
        uses: leafo/gh-actions-lua@v10
        with:
          luaVersion: ${{ matrix.luaVersion }}
      - name: Test
        run: |
          lua tests/run_all.lua
